export const productos = [
    {
      id: 1,
      name: "Remera roja",
      price: 100,
      offert: true,
      offert_price: 80,
      firstProduct: true,
      available: true,
      salient: true,
      available: true,
      category: "Remeras",
      image: "https://source.unsplash.com/400x300/?shirt"
    },
    {
      id: 2,
      name: "Zapatos negros",
      price: 200,
      offert: false,
      offert_price: null,
      firstProduct: true,
      salient: true,
      available: true,
      category: "Zapatos",
      image: "https://source.unsplash.com/400x300/?shoes"
    },
    {
      id: 3,
      name: "Anillo de plata",
      price: 150,
      offert: true,
      offert_price: 120,
      firstProduct: true,
      salient: false,
      category: "Accesorios",
      image: "https://source.unsplash.com/400x300/?ring"
    },
    {
      id: 4,
      name: "Laptop Asus",
      price: 300,
      offert: false,
      offert_price: null,
      firstProduct: true,
      salient: true,
      available: true,
      category: "Tecnología",
      image: "https://source.unsplash.com/400x300/?laptop"
    },
    {
      id: 5,
      name: "Remera azul",
      price: 250,
      offert: true,
      offert_price: 200,
      firstProduct: true,
      salient: false,
      category: "Remeras",
      image: "https://source.unsplash.com/400x300/?blue+shirt"
    },
    {
      id: 6,
      name: "Reloj de cuero",
      price: 175,
      offert: false,
      offert_price: null,
      firstProduct: true,
      salient: false,
      category: "Accesorios",
      image: "https://source.unsplash.com/400x300/?watch"
    },
    {
      id: 7,
      name: "Auriculares Sony",
      price: 225,
      offert: true,
      offert_price: 180,
      firstProduct: true,
      salient: true,
      available: true,
      category: "Tecnología",
      image: "https://source.unsplash.com/400x300/?headphones"
    },
    {
      id: 8,
      name: "Zapatillas Nike",
      price: 275,
      offert: false,
      offert_price: null,
      firstProduct: true,
      salient: true,
      available: true,
      category: "Zapatos",
      image: "https://source.unsplash.com/400x300/?nike"
    },
    {
      id: 9,
      name: "Remera verde",
      price: 120,
      offert: true,
      offert_price: 100,
      firstProduct: true,
      salient: false,
      available: true,
      category: "Remeras",
      image: "https://source.unsplash.com/400x300/?green+shirt"
    },
    {
      id: 10,
      name: "Smartphone Samsung",
      price: 350,
      offert: false,
      offert_price: null,
      firstProduct: true,
      salient: false,
      available: true,
      category: "Tecnología",
      image: "https://source.unsplash.com/400x300/?samsung+phone"
    }
    ];